DROP TYPE IF EXISTS event_state CASCADE;
CREATE TYPE event_state AS ENUM ('PENDING', 'PUBLISHED', 'CANCELED', 'REVISION_REQUIRED');

DROP TYPE IF EXISTS request_status CASCADE;
CREATE TYPE request_status AS ENUM ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED');

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    name  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000)    NOT NULL,
    category_id        BIGINT           NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    confirmed_requests INTEGER     DEFAULT 0,
    created_on         TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    description        VARCHAR(7000)    NOT NULL,
    event_date         TIMESTAMP        NOT NULL,
    initiator_id       BIGINT           NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    lat                DOUBLE PRECISION NOT NULL,
    lon                DOUBLE PRECISION NOT NULL,
    paid               BOOLEAN     DEFAULT FALSE,
    participant_limit  INTEGER     DEFAULT 0,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN     DEFAULT TRUE,
    state              event_state DEFAULT 'PENDING',
    title              VARCHAR(120)     NOT NULL,
    views              BIGINT      DEFAULT 0
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    event_id     BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       request_status DEFAULT 'PENDING',
    UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN DEFAULT FALSE,
    title  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS event_reviews
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    comment    VARCHAR(2000) NOT NULL,
    status     VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_reviews_event ON event_reviews (event_id);

CREATE INDEX IF NOT EXISTS idx_events_category ON events (category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator ON events (initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON events (state);
CREATE INDEX IF NOT EXISTS idx_requests_event ON requests (event_id);
CREATE INDEX IF NOT EXISTS idx_requests_requester ON requests (requester_id);
CREATE INDEX IF NOT EXISTS idx_compilation_events_compilation ON compilation_events (compilation_id);
