server:
  port: 8080

statistics:
  client:
    url: http://stats-server:9090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ewm
    username: ewm
    password: ewm

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: DEBUG
        web: DEBUG
        web.servlet.DispatcherServlet: TRACE
