CREATE SEQUENCE IF NOT EXISTS hits_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(255)                            NOT NULL,
    uri       VARCHAR(255)                            NOT NULL,
    ip        VARCHAR(255)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT hits_pkey PRIMARY KEY (id)
);